amba:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name designatecarina_mdns_1"

bind-1:
  build: .
  ports:
    - "53"
    - "953"
    - "53/udp"
    - "953/udp"
    - "5358/tcp"
    - "5358/udp"
  links:
    - "amba:mdns"

  command: run-bind-with-agent.sh

bind-2:
  build: .
  ports:
    - "53"
    - "953"
    - "53/udp"
    - "953/udp"
    - "5358/tcp"
    - "5358/udp"
  links:
    - "amba:mdns"

  command: run-bind-with-agent.sh

mysql:
  build: .

  ports:
    - "3306"

  command: /usr/bin/mysqld_safe

rabbit:
  image: rabbitmq

  environment:
    RABBITMQ_DEFAULT_USER: designate
    RABBITMQ_DEFAULT_PASS: designate

  ports:
    - "5672"

memcached:
  image: memcached
  ports:
    - "11211:11211"

api:
  build: .
  links:
    - rabbit

  ports:
    - "9001"

  command: designate-api

central:
  build: .
  links:
    - rabbit
    - mysql

  command: designate-central

mdns:
  build: .
  links:
    - rabbit
    - mysql
    - bind-1
    - bind-2
  ports:
    - "5354"

  command: designate-mdns


poolmanager:
  build: .
  links:
    - mdns
    - bind-1
    - bind-2
    - rabbit
    - memcached
    - mysql

  command: designate-pool-manager

zonemanager:
  build: .
  links:
    - rabbit
    - memcached
    - mysql

  command: designate-zone-manager
