bind:
  build: .
  ports:
    - "53"
    - "953"
    - "53/udp"
    - "953/udp"

  command: named -g

dbdata:
  build: .
  volumes:
    - /var/lib/mysql
  command: /bin/true

mysql:
  build: .

  volumes_from:
    - dbdata

  ports:
    - "3306"

rabbit:
  image: rabbitmq

  environment:
    RABBITMQ_DEFAULT_USER: designate
    RABBITMQ_DEFAULT_PASS: designate

  ports:
    - "5672"

memcached:
  image: memcached
  ports:
    - "11211:11211"

zookeeper:
  image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
  ports:
    - "2181:2181"

api:
  build: .
  links:
    - rabbit

  ports:
    - "9001:9001"

  command: designate-api

central:
  build: .
  links:
    - rabbit
    - mysql

  command: designate-central

mdns:
  build: .
  links:
    - rabbit
    - mysql
  ports:
    - "5354:5354"

  command: designate-central


poolmanager:
  build: .
  links:
    - rabbit
    - memcached
    - mysql

  command: designate-pool-manager

zonemanager:
  build: .
  links:
    - rabbit
    - memcached
    - mysql

  command: designate-zone-manager
