version: '2'

services:
  base:
    build:
      context: .
      args:
        DESIGNATE_CONF: etc/designate/designate.conf

  bind-1:
    image: designatecarina_base
    ports:
      - "53"
      - "953"
      - "53/udp"
      - "953/udp"
      - "5358/tcp"
      - "5358/udp"

    command: run-bind-with-agent.sh

  bind-2:
    image: designatecarina_base
    ports:
      - "53"
      - "953"
      - "53/udp"
      - "953/udp"
      - "5358/tcp"
      - "5358/udp"

    command: run-bind-with-agent.sh

  mysql:
    image: designatecarina_base

    ports:
      - "3306"

    command: /usr/bin/mysqld_safe

  rabbit:
    image: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: designate
      RABBITMQ_DEFAULT_PASS: designate

    ports:
      - "5672"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  api:
    image: designatecarina_base
    ports:
      - "9001"
    command: designate-api

  central:
    image: designatecarina_base
    command: designate-central

  mdns:
    image: designatecarina_base
    ports:
      - "5354"
    command: designate-mdns


  poolmanager:
    image: designatecarina_base
    command: designate-pool-manager

  zonemanager:
    image: designatecarina_base
    command: designate-zone-manager
